# Generated by Django 6.0 on 2026-01-04 11:01

import admissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('admission_number', models.CharField(blank=True, default=admissions.models.Application.generate_admission_no, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('id_copy', models.FileField(upload_to='applications/id_copies/')),
                ('certificate', models.FileField(upload_to='applications/certificates/')),
                ('application_code', models.CharField(default=admissions.models.Application.generate_application_code, editable=False, max_length=12, unique=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program')),
            ],
        ),
    ]
